"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelSync = void 0;
class ModelSync {
    static model;
    static modelQuery = '';
    static attributes;
    static options;
    static Instance;
    static define() {
        // define(handler: MySQLHandler): MySQLHandler & this {
        let schema = '';
        Object.entries(this.attributes)
            .forEach(([name, options]) => {
            let columnSQL = `\`${name}\` ${options.type}`;
            if (options.values) {
                columnSQL += ` (${options.values.map(value => `'${value}'`).join(', ')})`;
            }
            if (options.allowNull && options.defaultValue !== undefined) {
                throw Error("Only a default value must be specified");
            }
            if (options.allowNull && !options.defaultValue) {
                columnSQL += " DEFAULT NULL";
            }
            else if (!options.allowNull && options.defaultValue == undefined) {
                columnSQL += " NOT NULL";
            }
            // Check for unique constraint
            else if (options.defaultValue !== undefined) {
                const defaultValue = options.defaultValue === null
                    ? "NULL"
                    : options.defaultValue === "CURRENT_TIMESTAMP"
                        ? "CURRENT_TIMESTAMP"
                        : `'${options.defaultValue}'`;
                columnSQL += ` DEFAULT ${defaultValue}`;
            }
            if (options.unique) {
                columnSQL += ' UNIQUE';
            }
            if (options.primaryKey)
                columnSQL += " PRIMARY KEY";
            if (options.autoIncrement)
                columnSQL += ` ${this.handleAutoIncrement(false)}`;
            if (options.references) {
                if (typeof options.references === "string") {
                    columnSQL += ` REFERENCES \`${options.references}\``;
                }
                else {
                    const { model, key } = options.references;
                    if (typeof model === "function" && "model" in model) {
                        columnSQL += ` REFERENCES \`${model.model}\` (\`${key}\`)`;
                    }
                    else {
                        columnSQL += ` REFERENCES \`${model}\` (\`${key}\`)`;
                    }
                }
            }
            if (options.onUpdate) {
                columnSQL += ` ON UPDATE ${options.onUpdate}`;
            }
            if (options.onDelete)
                columnSQL += ` ON DELETE ${options.onDelete}`;
            // return columnSQL;
            schema += (schema ? ",\n  " : "") + columnSQL;
        });
        this.modelQuery = `
CREATE TABLE IF NOT EXISTS \`${this.model}\` (
  ${schema}
) ${this.getEngineOptions()};`.trim();
    }
    static getEngineOptions() {
        // if (this.dbType === 'PostgreSQL') {
        //     return ''; // PostgreSQL does not require engine or charset settings.
        // } else {
        return `${this.options.auto_increment ? `AUTO_INCREMENT = ${this.options.auto_increment} ` : ""}ENGINE = ${this.options.engine ?? 'InnoDB'}
  DEFAULT CHARSET = ${this.options.charset || 'utf8mb4'}
  COLLATE = ${this.options.collation || 'utf8mb4_unicode_ci'}`;
    }
    // #formatDefaultValue(value: any) {
    //     if (typeof value === 'string') {
    //         return `'${value}'`;
    //     } else if (value === 'CURRENT_TIMESTAMP') {
    //         return 'CURRENT_TIMESTAMP';
    //     } else {
    //         return value;
    //     }
    // }
    static handleAutoIncrement(autoIncrementIdentity) {
        // if (this.dbType === 'PostgreSQL') {
        //     if (autoIncrementIdentity) {
        //         return 'GENERATED BY DEFAULT AS IDENTITY';
        //     } else {
        // return 'SERIAL';
        // }
        // } else {
        return 'AUTO_INCREMENT'; // For MySQL
        // }
    }
    // static async create(values: any) {
    //     await this.runHooks('beforeCreate', values);
    //     const columns = Object.keys(this.attributes).join(', ');
    //     const placeholders = Object.keys(this.attributes)
    //         .map(() => '?')
    //         .join(', ');
    //     const valuesArray = Object.values(values);
    //     const query = `INSERT INTO \`${this.model}\` (${columns}) VALUES (${placeholders})`;
    //     const result = await this.Instance.execute(query, valuesArray);
    //     await this.runHooks('afterCreate', result);
    //     return result;
    // }
    // Drop a model if it exists
    static async drop() {
        const query = `DROP TABLE IF EXISTS \`${this.model}\``;
        return await this.Instance.execute(query);
    }
    static async sync(force = false) {
        if (force) {
            // Drop the table if `force` is true
            await this.drop();
        }
        return this.Instance.execute(this.modelQuery);
    }
}
exports.ModelSync = ModelSync;
